version: 0.1

phases:
  pre_build:
    commands:
      # install eksctl
      - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - sudo mv /tmp/eksctl /usr/local/bin
  build:
    commands:
      - set -x # Echo Commands
      - python3 ./parse_and_build.py
